services:
  - type: web
    name: matthews-music-bot
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && apt-get update && apt-get install -y ffmpeg
    startCommand: python3 -m bot
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false